### ISSUE TITLE
mount failed when the target's filesystem is not loaded.

### ISSUE THREAD

**Issue by HSwift** [rmb122/usbmount#1]
When the USB device uses an unloaded file system such as ntfs, the mount failed.

usbmount output:

`failed to mount /dev/sda1 to /var/run/media/user/p1: Invalid argument (os error 22)`

Is it possible to automatic load the kernel module for corresponding filesystem?

**Comment by rmb122** [comment]
This problem should fixed in https://github.com/rmb122/usbmount/commit/4df391c08ff332c68bdc13954c57121e0008a8db
